PayAPI: 
    Db: 
        LogsConnString: 
            settings-key: LogsConnString
            types: [AzureTableStorage, Tag]
         
    PaymentRequestDueDate: 
        settings-key: PayAPI-PaymentRequestDueDate
        types: [Tag] 
    PayInvoicePortalUrl: 
        settings-key: PayInvoicePortalUrl
        types: [Tag] 
    TransactionUrl: 
        settings-key: PayAPI-TransactionUrl 
    JwtSecurity: 
        Issuer: 
            settings-key: PayAPI-JwtSecurity-Issuer 
        Audience: 
            settings-key: PayAPI-JwtSecurity-Audience 
        Key: 
            settings-key: PayAPI-JwtSecurity-Key 
        TokenLifetime: 
            settings-key: PayAPI-JwtSecurity-TokenLifetime
         
    CacheExpirationPeriods: 
        IataBillingCategories: 
            settings-key: PayAPI-CacheExpirationPeriods-IataBillingCategories 
        MerchantLogoUrl: 
            settings-key: PayAPI-CacheExpirationPeriods-MerchantLogoUrl 
        MerchantName: 
            settings-key: PayAPI-CacheExpirationPeriods-MerchantName
         
    Iata: 
        AssetsMap: 
            Values: 
                settings-key: PayAPI-Iata-AssetsMap-Values
                types: [Json]
             
        CashoutAssets: 
            Assets: 
                settings-key: PayAPI-Iata-CashoutAssets-Assets
                types: [JsonArray]
            
         
    Merchant: 
        MerchantDefaultLogoUrl: 
            settings-key: PayAPI-Merchant-MerchantDefaultLogoUrl
        
     
PayAuthServiceClient: 
    ServiceUrl: 
        settings-key: PayAuthServiceUrl
        types: [Tag]
     
PayCallbackServiceClient: 
    ServiceUrl: 
        settings-key: PayCallbackServiceUrl
        types: [Tag]
     
PayHistoryServiceClient: 
    ServiceUrl: 
        settings-key: PayHistoryServiceUrl
        types: [Tag]
     
PayInternalServiceClient: 
    ServiceUrl: 
        settings-key: PayInternalServiceUrl
        types: [Tag]
     
PayInvoiceServiceClient: 
    ServiceUrl: 
        settings-key: PayInvoiceServiceUrl
        types: [Tag]
     
PayPushNotificationsServiceClient: 
    ServiceUrl: 
        settings-key: PayPushNotificationsServiceUrl
        types: [Tag]
     
PayVolatilityServiceClient: 
    ServiceUrl: 
        settings-key: PayVolatilityServiceUrl
        types: [Tag]
     
AssetsServiceClient: 
    ServiceUrl: 
        settings-key: AssetsServiceUrl 
    ExpirationPeriod: 
        settings-key: AssetsServiceExpirationPeriod
     
EthereumServiceClient: 
    ServiceUrl: 
        settings-key: EthereumApiServiceUrl 
    HotwalletAddress: 
        settings-key: EthereumApiHotwalletAddress
     
IataApiServiceClient: 
    ServiceUrl: 
        settings-key: IataApiServiceUrl 
    ApiKey: 
        settings-key: IataApiKey
     
MarketProfileServiceClient: 
    ServiceUrl: 
        settings-key: MarketProfileServiceUrl
     
SlackNotifications: 
    AzureQueue: 
        ConnectionString: 
            settings-key: SlackNotificationsConnString
            types: [AzureTableStorage] 
        QueueName: slack-notifications
         
    ThrottlingLimitSeconds: 
        settings-key: SlackNotificationsThrottlingLimit
     
MonitoringServiceClient: 
    MonitoringServiceUrl: 
        settings-key: MonitoringServiceUrl